### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by aNDOhACK** [4w4k3/Insanity-Framework#18]
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "dammed.py", line 445, in <module>
    main()
  File "dammed.py", line 428, in main
    asker() 
  File "dammed.py", line 199, in asker
    os.rename('dist/new.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by nicatmazanli** [comment]
Try to run this command `sudo python2.7 insanity.py`
