### ISSUE TITLE
Cant use the tool

### ISSUE THREAD

**Issue by MarieUwU-nerd** [4w4k3/Insanity-Framework#2]
I got this error : 
```
InSaNiTy > D
Traceback (most recent call last):
  File "enc.py", line 8, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
Type LHOST: 
```
or this : 
```
Traceback (most recent call last):
  File "dammed.py", line 439, in <module>
    main()
  File "dammed.py", line 304, in main
    begin()
  File "dammed.py", line 36, in begin
    template = open('Templates/insane_enc.py', 'r')
IOError: [Errno 2] No such file or directory: 'Templates/insane_enc.py'

```

**Comment by 4w4k3** [comment]
Try manually:
sudo wine /root/.wine/drive_c/Python27/python.exe -m pip uninstall Crypto
sudo wine /root/.wine/drive_c/Python27/python.exe -m pip uninstall pycrypto
sudo wine /root/.wine/drive_c/Python27/python.exe -m pip install pycrypto

**Comment by 4w4k3** [comment]
I will revise full code tonight, please wait.

**Comment by 4w4k3** [comment]
Check out now
